--- 
- name: toptour api
  hosts: trd
  become: yes

  vars:
    nginx_app_config_template: "api.trd.toptour.no.j2"
    nginx_app_domain_name: "api.trd.toptour.no"
    nginx_app_webroot: /var/www/{{nginx_app_domain_name}}
    letsencrypt_email: kjartanbjorset@gmail.com 
    
    travis_ci_user: travis
    travis_ci_web_group: web
    travis_ci_pub_deploy_key: "/home/kjartan/.ssh/id_rsa_travis.pub"

  pre_tasks: 
    - apt: update_cache=yes

  roles:
    - role: kjartab.nginx-certbot-app
    - role: ansible-role-travis-ci-app

  # tasks:
    # - local_action: shell cd {{playbook_dir}} && npm install --no-bin-links
    #   become_user: "{{ansible_user}}"
    # - local_action: shell rollup {{playbook_dir}}
    
  # roles: 
  #   - kjartab.nginx-letsencrypt
    # - local_action: rollup 
  # roles:
  #   - geerlingguy.nodejs
  #   - angstwad.docker_ubuntu
  # tasks:
  #   - copy: src=../{{playbook_dir}}/package.json dest=/opt/toptour-api
