--- 
- name: toptour api
  hosts: "{{ hosts_input | default('default') }}"
  become: yes

  vars:
    letsencrypt_email: kjartanbjorset@gmail.com
    letsencrypt_domain_name: api.trd.toptour.no
    
    nginx_web_root: /var/www
    nginx_config_name: toptourapiconfig.j2

  roles:
    - role: kjartab.nginx
    - role: kjartab.nginx-letsencrypt
  


  # tasks:
    # - local_action: shell cd {{playbook_dir}} && npm install --no-bin-links
    #   become_user: "{{ansible_user}}"
    # - local_action: shell rollup {{playbook_dir}}
    
  # roles: 
  #   - kjartab.nginx-letsencrypt
    # - local_action: rollup 
  # roles:
  #   - geerlingguy.nodejs
  #   - angstwad.docker_ubuntu
  # tasks:
  #   - copy: src=../{{playbook_dir}}/package.json dest=/opt/toptour-api
