--- 
- name: toptour api
  hosts: regn
  become: yes

  vars:
    nginx_app_config_template: "api.toptour.no.j2"
    nginx_app_domain_name: "api.toptour.no"
    nginx_app_webroot: /var/www/{{nginx_app_domain_name}}
    letsencrypt_email: kjartanbjorset@gmail.com 
    
    toptour_deploy_user: toptour
    travis_ci_user: "{{toptour_deploy_user}}"
    travis_ci_web_group: web
    travis_ci_pub_deploy_key: "/home/kjartan/.ssh/id_rsa_travis.pub" 
    cookie_domain: "toptour.no"

  pre_tasks:

    - apt: update_cache=yes

    - user: name={{toptour_deploy_user}} groups=docker,web

    - authorized_key: user={{toptour_deploy_user}} key="{{ lookup('file', '{{travis_ci_pub_deploy_key}}') }}"


    - lineinfile:
        regexp: 'export GOOGLE_CLIENT_ID='
        path: /home/{{toptour_deploy_user}}/.bashrc
        line: 'export GOOGLE_CLIENT_ID={{google_client_id}}'

    - lineinfile:
        regexp: 'export GOOGLE_CLIENT_SECRET='
        path: /home/{{toptour_deploy_user}}/.bashrc
        line: 'export GOOGLE_CLIENT_SECRET={{google_client_secret}}'

    - lineinfile:
        regexp: 'export API_BASE_NAME='
        path: /home/{{toptour_deploy_user}}/.bashrc
        line: 'export API_BASE_NAME={{nginx_app_domain_name}}'

    - lineinfile:
        regexp: 'export COOKIE_DOMAIN='
        path: /home/{{toptour_deploy_user}}/.bashrc
        line: 'export COOKIE_DOMAIN={{cookie_domain}}'
        
    - file:
        path: /home/{{toptour_deploy_user}}/toptour
        state: directory
        recurse: yes
        owner: "{{toptour_deploy_user}}"

    - file:
        path: /usr/share/elasticsearch/data
        state: directory
        recurse: yes
        owner: "{{toptour_deploy_user}}"


    - lineinfile: 
        path: /etc/sysctl.conf
        line:  vm.max_map_count=262144

    - command: sysctl --system
  
  roles:
    - role: kjartab.nginx-certbot-app
    # - role: ansible-role-travis-ci-app

  # tasks:
    # - local_action: shell cd {{playbook_dir}} && npm install --no-bin-links
    #   become_user: "{{ansible_user}}"
    # - local_action: shell rollup {{playbook_dir}}
    
  # roles: 
  #   - kjartab.nginx-letsencrypt
    # - local_action: rollup 
  # roles:
  #   - geerlingguy.nodejs
  #   - angstwad.docker_ubuntu
  # tasks:
  #   - copy: src=../{{playbook_dir}}/package.json dest=/opt/toptour-api