sudo: required
dist: trusty
addons:
  ssh_known_hosts: api.trd.toptour.no
cache:
  directories:
  - node_modules
language: node_js
node_js:
- '7'
install: true

after_success:
- docker build -t "kjartanb/toptour-api" ./
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push "kjartanb/toptour-api"; fi

before_deploy:
- openssl aes-256-cbc -K $encrypted_9d805cca1e1c_key -iv $encrypted_9d805cca1e1c_iv
  -in id_rsa_travis.enc -out /tmp/id_rsa_travis -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa_travis
- ssh-add /tmp/id_rsa_travis

deploy:

  - provider: script
    skip_cleanup: true
    script: rsync -rav --no-perms --delete-after --quiet $TRAVIS_BUILD_DIR/ --include=docker-compose* --include=deploy.sh travis@api.trd.toptour.no:/home/travis/toptour/
    on:
      branch: master

  - provider: script
    script: ssh travis@api.trd.toptour.no source .bashrc; chmod +x deploy.sh; ./deploy.sh
    on:
      branch: master

env:
  global:
  - secure: k6FxUxwrDgMjInMNrWLR2uU8Zu+QWmQ0rr42OA0/bApFsY1AeGTzeb60eHl/vsCa5DNiekKUhN+ro/J8tkNRx2FpqRaBy1/b2fZRUKHWc5PoaLezIRqjHugKShvrwQjEAOCtve40Wk9+ZFHdfwZQZ6P63uG4Q/zxtlmzEaq+KbVDj0Aorf6HQQYL5+GdH9fDSPnno8x6NNAk2nyr0qsWq/mxrygl7v5y+0sRk8hkNRI6XvUvTgiNAtACpP2Jnyr12FFfHrWGMp6RW0xzF5Lt4r7WSmBkfuKUp4955qsGl97OIVwNDxPF9GVrAM0HHjoFYfdM9aBGttehcwRWoEI0fFdfqbPzTI79e6wamrHwT5ySYcaWcI0wdm772BYCecNCWkHTi/o/4sAvvUWLIHHFDkxUdBv2x+X7SHkbvND2d5tLj9pbeLY+OtJI3HmQdlKiuMD0kz4sKuTWloDKy0QDlgu8l9fB7VkCouBYyMBqWb+K3aW61wG1/AkwI8OmHQhv/jN3cu06Pa7wavWW+k/qZcC2n/se0ygA8gK3YLWBBzulVPnj7lEqtj1r39NRpuAn9kuHxAybv/xCIVvWscBoJDJWT/PRPXuW7h6fL9y7tjl8YZxvOJggA9UBBe5NqsdYTNEs3w8BEp134tOjjGHIUWY3VE0B5eD5A7D5wkiAOT4=
  - secure: yhjncrfWFJHNOjsrnL4P0i2YiEbF0LA+n74Voc9P/ANYZMqbJv/AIzV0R5B4WdRb4VtuMujfKufH/Fj8P1meKJj99/kG0pXzpujM5oHrVa7ylKsC2ct+rlcnPmWBiViTJ5WQFMlWvYb9BgJ1q/tt7rWDrieDzlOyZnzobUXjbTivP3Eejgr9sqqkfblBYSVHN4NE/4Sovs04XErfGlYRTLe6qaz5zmfUCQ9HeAPEsl4nl7+Ux/R6JiT0qkM6LcWoZ1IVQQKCgDhiUCSIPK1gUpj3bJ9qsbEE/CZ1C5do6ZNnKxwOcmAfHUli9aFQZ5DXQihmU7iie6doGQeI3UyDGCsfkRd29SJ9RZz6EWTtz1pVKdnyIMI60HeS9gO3PrN/k+NRAPsnmcBvt/OHsHs87v7/EsbjV/CEh4Eas6zX2kPt6YWgRNFrAIPQpF4YfPvQ4y+ETmc8JOduBxbejtJjsj2tfLjhvUzQs9X56hZKzeEwqeh9PhY35jNFXq8NFGsEBBDPvjEb/i6Ery9e3DaC5HXl187dtmjz+uVJqUwQvy5KfGkAGSZLVY7jXX1sxzDTWNFk472BtzYsKHWtSr58p00JnQ7/XVK4zLI2Vsr7Uo5TgWas0+2t0j3dI5P+cR2+0eL7I5lClju7A/ANFNkKKkf/vAAzcespRx8mCoGoims=
  - secure: en0nDgfl8Y38QNyWHwd2+pgd5+MY/iyMuuyKpZ2zNlJZaSJqDfefsKjbgNCBECw9aE/bS3jhre619mTz1YUD6zaE4wnjyK/tMJYxezRb3LUV37YU5CQciM1X6e15uujq3vJCux1OvV3lXw1hyRgS51JTPPV/R60mYPFqBGBKydtg/Ap4IkkLwt2GHNKaYjtswDNPKKn0AK2HjxiRypns0BUNJrwWz9QdCnzCezVOC7ICvuJ/oKCLqZBr4GMW2g03lwjWxGgDoQltyR5bXWqj3wj7PDGivkRR9f7eSszbFxnMPRl6RO4iSgp0SEwbLSAXrx4zz8WerjdIrop09Kty24YC5umxlqn8DqKnU9LNn1f8uoN47yGG2QSpY/8AskIPfG4Bc797YwwMLiRkw2CN7koyCe7HCmXexdgj5/4X79nJbpH3GQVr2xcBaIBrKi7ZMjgde48sRtyn2UeIgaZqSkl9HcLZHwOkeQ3izMp852ecJw/BPEgt6DtUXsWOTCakCeqA71KdXWUchZjYYXRoY8qpbiV99PwqAnScKMjr6jhtSKsCgefHO0QxFXFsdNXR8WBNCJ2PdQBbGSRRCIKrMOpytOBWkO0bX3jMRXC2Z1WXCH93u0wBD15kUmPCouTxv29MgUBhiR0vKQRCues2nvYxBfiG9K2LNpC4zVOo8lI=
  - secure: oeEktsuV1OFXMUHVylGRrhgka+0iafqz7MOZoxDXlxTHtNfdAsipHLmdxBAKYKnQlTb/eAyodOoTs1H+5UtHGuh4WkS4JWw4DVoBEFOD7DaRM8V9hfLD3ZZIA++++MQr6jKUpGAN5SdVIA5YFieFui6/VXW2R/tMnXcwfrJp5SQR2PSMawHwDslWCyYiqhEh4EzXOgh8IH2l2tLT7GuibmRHoPkH7IYPIXtb4YrcjZr0SwYKFeTmbrt5VEsaTirUtAf6ejYp36QhGLCeY+L3txNbrNwmAHf8OzprsdWL341UI4+CEdmmJXpxtaagi4cUP2Lgg3xxfa7PUkkJ0/wNggDR6TQetVn3xsuyW6WKaqFebsmPTaFFKSdC5BGfL5kLHAj4JB5ToryhhAhcAZ42HCnD8QViiWo7Xx62zlfiaBxUNq63pIPvm6jkKLMhtpDk0ImkER8aPd3gBVc64EuKHsjdyAIm392G1qfVnTWLng31odiI+gyspC1kjee7iZXOtQfweFvakkY9NMpgtP8ShlZYDlaj6LHOEaehoVzMgkKLEIBheJCJy/dWmUYSICsALy6S9On2+GTzUa3Q0XjiYyAAo8apgIb+C/n9ZQQwpvaotAjgXsJADVEli++7GSbP04fQCX6DaxAYjimMl5lVio0PbSWI8G5arRJuJl2nfzE=
  - secure: SR967IgddDUFJispkY+mlK49f1W/bua7bUNZnV2KATDsBF7OFndDXdLjox4mvw71Qqor3gmzlRrqcP1tiG1+CEbOHK1Po7kgDKe7R7UfauPPIUahwEzsg+VE1NJyfxfSkd0vOfILE/2JUvocgy/Ppf7cTdMkVJOPKXYGKp/uUi/9V0vuIW89Salgyon8S/WwEnwEfmtZ6rVJttfnk51fqgMHqPsT9mJzRsXcWzhDCUWn7rlg+hGS9hZVbmPE7BVfFMA5V2WnssjvuG638RluEvaGN3H/qWeYXCSnF26BHZneGR68oU3jDspWfGUx/jlY94kYw8HgcwHs7Nr84R8xywLzpnDM9eNcRJRmaJLNhQz/8b3AzBirjAH/CX5imw+mmeNRweZLK7nt7YBrAbUnoz8RXJmeXlGKqMjcVeomFGqISOnIsjLpMQ0FI6PyMWxajVgjSG0p0Tx5r5IsgiFT5o/s+2pU5DlNM4RZ/kyppWoBBjBttNjLXaDrtRMmjtJr/tpO2I0ktq3UpfzahGeBhuKjOWnxMDencqVznQQ+TBIBW/y7/mYqhCGABSjjV61RnGYhqNNzWEqEP6PPmHmsfEG/0iy4p2h1NabXRjHPsDXH/NwaBjC0428Io/kL18qp1BnItUusOUZVormGPLXzIHZWnchvbp17zKhPhu8cSuU=
