sudo: required
dist: trusty
addons:
  ssh_known_hosts: api.trd.toptour.no

language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
install: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_9d805cca1e1c_key -iv $encrypted_9d805cca1e1c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -rav --no-perms --delete-after --quiet $TRAVIS_BUILD_DIR travis@api.trd.toptour.no:/home/travis/api.trd.toptour.no
  on:
    branch: master
