version: "3"
services:

  api:
    image: kjartanb/toptour-api
    ports:
      - "5042:3000"
    deploy:
      restart_policy:
        condition: always

    environment:
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET