version: "3"
services:

  api: 
    build: .
    ports:
      - "5042:3000"
    deploy:
      restart_policy:
        condition: always
    
    environment:
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - ES_SERVER=elasticsearch
      - ELASTIC_USER=$ELASTIC_USER
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - API_BASE_NAME=$API_BASE_NAME
      - COOKIE_DOMAIN=$COOKIE_DOMAIN 

networks:
  dbnet: